[package]
name = "toboggan_traj"
version = "0.1.0"
authors = ["Jeffrey Kim <kimjeffrey96@gmail.com>"]
edition = "2018"

[lib]
name = "f_reader"
path = "../../libs/f_reader/src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
